; generated by weavec1
; source: test/10_string_literal.wir
; core-version: 2

; declarations

declare i32 @puts(ptr)

; string literals

@.str0 = private unnamed_addr constant [17 x i8] c"hello from weave\00"

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; print
  %t0 = getelementptr [17 x i8], ptr @.str0, i64 0, i64 0
  call i32 @puts(ptr %t0)
  ; return
  ret i32 42
}

