; generated by weavec1
; source: test/11_const_i64.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  %x.addr = alloca i64
  store i64 42, ptr %x.addr
  ; return
  %t0 = load i64, ptr %x.addr
  %t1 = trunc i64 %t0 to i32
  ret i32 %t1
}

