; generated by weavec1
; source: test/12_i64_arithmetic.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let a
  %a.addr = alloca i64
  store i64 20, ptr %a.addr
  ; let b
  %b.addr = alloca i64
  store i64 2, ptr %b.addr
  %t0 = load i64, ptr %b.addr
  %t1 = mul i64 %t0, 11
  ; let c
  %c.addr = alloca i64
  store i64 %t1, ptr %c.addr
  %t2 = load i64, ptr %a.addr
  %t3 = load i64, ptr %c.addr
  %t4 = add i64 %t2, %t3
  ; let d
  %d.addr = alloca i64
  store i64 %t4, ptr %d.addr
  ; return
  %t5 = load i64, ptr %d.addr
  %t6 = trunc i64 %t5 to i32
  ret i32 %t6
}

