; generated by weavec1
; source: test/14_bool_ops.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = or i1 0, 1
  %t1 = and i1 1, %t0
  br i1 %t1, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

