; generated by weavec1
; source: test/15_ptr_null.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = icmp eq ptr null, null
  br i1 %t0, label %then0, label %else0
then0:
  ; then
  ; if condition
  %t1 = icmp ne ptr null, null
  br i1 %t1, label %then1, label %else1
then1:
  ; then
  ; return
  ret i32 0
else1:
  ; else
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

