; generated by weavec1
; source: test/18_store_load_i8.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 1)
  ; let p
  %p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
  ; if condition
  %t1 = load ptr, ptr %p.addr
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 0
else0:
  ; else
  br label %done0
done0:
  ; store
  %t3 = load ptr, ptr %p.addr
  %t4 = add i32 0, 42
  %t5 = trunc i32 %t4 to i8
  store i8 %t5, ptr %t3
  %t6 = load ptr, ptr %p.addr
  %t7 = load i8, ptr %t6
  %t8 = zext i8 %t7 to i32
  ; let x
  %x.addr = alloca i32
  store i32 %t8, ptr %x.addr
  ; call_void
  %t9 = load ptr, ptr %p.addr
  call void @free(ptr %t9)
  ; return
  %t10 = load i32, ptr %x.addr
  ret i32 %t10
}

