; generated by weavec1
; source: test/19_call_void.wir
; core-version: 2

; declarations

declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; call_void
  %t0 = getelementptr i8, ptr null, i64 0
  call void @free(ptr %t0)
  ; return
  ret i32 42
}

