; generated by weavec1
; source: test/30_i64_sub_eq.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = sub i64 50, 8
  %t1 = icmp eq i64 %t0, 42
  br i1 %t1, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

