; generated by weavec1
; source: test/39_i64_ge_gt.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = icmp sgt i64 10, 9
  br i1 %t0, label %then0, label %else0
then0:
  ; then
  br label %done0
else0:
  ; else
  ; return
  ret i32 0
done0:
  ; if condition
  %t1 = icmp sge i64 10, 10
  br i1 %t1, label %then1, label %else1
then1:
  ; then
  ; return
  ret i32 42
else1:
  ; else
  ; return
  ret i32 0
}

