; generated by weavec1
; source: test/40_call_bool_direct.wir
; core-version: 1

; function: is_answer
; params: i32
; returns: i1
define i1 @is_answer(i32 %x) {
entry:
  ; return
  %t0 = icmp eq i32 %x, 42
  ret i1 %t0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t1 = call i1 @is_answer(i32 42)
  br i1 %t1, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

