; generated by weavec1
; source: test/43_if_fallthrough_join.wir
; core-version: 2

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  %x.addr = alloca i32
  store i32 0, ptr %x.addr
  ; if condition
  %t0 = icmp slt i32 1, 2
  br i1 %t0, label %then0, label %else0
then0:
  ; then
  ; set x
  %t1 = add i32 0, 42
  store i32 %t1, ptr %x.addr
  br label %done0
else0:
  ; else
  ; set x
  %t2 = add i32 0, 0
  store i32 %t2, ptr %x.addr
  br label %done0
done0:
  ; return
  %t3 = load i32, ptr %x.addr
  ret i32 %t3
}

