; generated by weavec1
; source: test/56_integration_multi_function_chain.wir
; core-version: 2

; function: calculate
; params: i32
; returns: i32
define i32 @calculate(i32 %x) {
entry:
  ; return
  %t0 = call i32 @helper_double(i32 %x)
  %t1 = call i32 @helper_square(i32 %x)
  %t2 = add i32 %t0, %t1
  ret i32 %t2
}

; function: helper_double
; params: i32
; returns: i32
define i32 @helper_double(i32 %n) {
entry:
  ; return
  %t3 = mul i32 %n, 2
  ret i32 %t3
}

; function: helper_square
; params: i32
; returns: i32
define i32 @helper_square(i32 %n) {
entry:
  ; return
  %t4 = mul i32 %n, %n
  ret i32 %t4
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t5 = call i32 @calculate(i32 5)
  ret i32 %t5
}

