; generated by weavec1
; source: test/57_integration_memory_flow.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: write_values
; params: ptr, i32
; returns: void
define void @write_values(ptr %buffer, i32 %count) {
entry:
  ; let i
  %i.addr = alloca i32
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond0
while.cond0:
  %t0 = load i32, ptr %i.addr
  %t1 = icmp slt i32 %t0, %count
  br i1 %t1, label %while.body0, label %while.end0
while.body0:
  ; while body
  ; store
  %t2 = load i32, ptr %i.addr
  %t3 = sext i32 %t2 to i64
  %t4 = mul i64 %t3, 4
  %t5 = getelementptr i8, ptr %buffer, i64 %t4
  %t6 = load i32, ptr %i.addr
  %t7 = mul i32 %t6, 10
  store i32 %t7, ptr %t5
  ; set i
  %t8 = load i32, ptr %i.addr
  %t9 = add i32 %t8, 1
  store i32 %t9, ptr %i.addr
  br label %while.cond0
while.end0:
  ret void
}

; function: sum_values
; params: ptr, i32
; returns: i32
define i32 @sum_values(ptr %buffer, i32 %count) {
entry:
  ; let sum
  %sum.addr = alloca i32
  store i32 0, ptr %sum.addr
  ; let i
  %i.addr = alloca i32
  store i32 0, ptr %i.addr
  ; while condition
  br label %while.cond1
while.cond1:
  %t10 = load i32, ptr %i.addr
  %t11 = icmp slt i32 %t10, %count
  br i1 %t11, label %while.body1, label %while.end1
while.body1:
  ; while body
  ; set sum
  %t12 = load i32, ptr %sum.addr
  %t13 = load i32, ptr %i.addr
  %t14 = sext i32 %t13 to i64
  %t15 = mul i64 %t14, 4
  %t16 = getelementptr i8, ptr %buffer, i64 %t15
  %t17 = load i32, ptr %t16
  %t18 = add i32 %t12, %t17
  store i32 %t18, ptr %sum.addr
  ; set i
  %t19 = load i32, ptr %i.addr
  %t20 = add i32 %t19, 1
  store i32 %t20, ptr %i.addr
  br label %while.cond1
while.end1:
  ; return
  %t21 = load i32, ptr %sum.addr
  ret i32 %t21
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t22 = call ptr @malloc(i64 20)
  ; let buffer
  %buffer.addr = alloca ptr
  store ptr %t22, ptr %buffer.addr
  ; call_void
  %t23 = load ptr, ptr %buffer.addr
  %t24 = add i32 0, 5
  call void @write_values(ptr %t23, i32 %t24)
  %t26 = load ptr, ptr %buffer.addr
  %t25 = call i32 @sum_values(ptr %t26, i32 5)
  ; let result
  %result.addr = alloca i32
  store i32 %t25, ptr %result.addr
  ; call_void
  %t27 = load ptr, ptr %buffer.addr
  call void @free(ptr %t27)
  ; return
  %t28 = load i32, ptr %result.addr
  ret i32 %t28
}

