; generated by weavec1
; source: test/59_new_operators.wir
; core-version: 2

; function: test_division
; params: none
; returns: i64
define i64 @test_division() {
entry:
  ; return
  %t0 = sdiv i64 42, 10
  %t1 = srem i64 42, 10
  %t2 = add i64 %t0, %t1
  ret i64 %t2
}

; function: test_bitwise_i32
; params: none
; returns: i32
define i32 @test_bitwise_i32() {
entry:
  ; return
  %t3 = shl i32 1, 3
  %t4 = and i32 12, 10
  %t5 = add i32 %t3, %t4
  %t6 = or i32 1, 2
  %t7 = xor i32 6, 4
  %t8 = add i32 %t6, %t7
  %t9 = sub i32 %t5, %t8
  ret i32 %t9
}

; function: test_bitwise_i64
; params: none
; returns: i64
define i64 @test_bitwise_i64() {
entry:
  ; return
  %t10 = shl i64 1, 3
  %t11 = and i64 12, 10
  %t12 = add i64 %t10, %t11
  %t13 = or i64 1, 2
  %t14 = xor i64 6, 4
  %t15 = add i64 %t13, %t14
  %t16 = sub i64 %t12, %t15
  ret i64 %t16
}

; function: test_shr
; params: none
; returns: i64
define i64 @test_shr() {
entry:
  ; return
  %t17 = lshr i32 16, 2
  %t18 = sext i32 %t17 to i64
  %t19 = lshr i64 32, 2
  %t20 = add i64 %t18, %t19
  ret i64 %t20
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t21 = call i64 @test_division()
  %t22 = call i32 @test_bitwise_i32()
  %t23 = sext i32 %t22 to i64
  %t24 = add i64 %t21, %t23
  %t25 = call i64 @test_bitwise_i64()
  %t26 = call i64 @test_shr()
  %t27 = add i64 %t25, %t26
  %t28 = add i64 %t24, %t27
  %t29 = trunc i64 %t28 to i32
  ret i32 %t29
}

