; generated by weavec1
; source: test/63_reused_local_name.wir
; core-version: 2

; function: first
; params: none
; returns: i32
define i32 @first() {
entry:
  ; let result
  %result.addr = alloca i32
  store i32 1, ptr %result.addr
  ; return
  %t0 = load i32, ptr %result.addr
  ret i32 %t0
}

; function: second
; params: none
; returns: i64
define i64 @second() {
entry:
  ; let result
  %result.addr = alloca i64
  store i64 2, ptr %result.addr
  ; set result
  %t1 = load i64, ptr %result.addr
  %t2 = add i64 %t1, 40
  store i64 %t2, ptr %result.addr
  ; return
  %t3 = load i64, ptr %result.addr
  ret i64 %t3
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; return
  %t4 = call i64 @second()
  %t5 = trunc i64 %t4 to i32
  ret i32 %t5
}

