; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @inc(i32 %x) {
entry:
%t0 = add i32 0, %x
%t1 = add i32 0, 1
%t2 = add i32 %t0, %t1
  ret i32 %t2
}

define i32 @main() {
entry:
%t4 = add i32 0, 41
%t3 = call i32 @inc(i32 %t4)
  ret i32 %t3
}

