; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i32 0, 40
%x.addr = alloca i32
  store i32 %t0, ptr %x.addr
%t1 = load i32, ptr %x.addr
%t2 = add i32 0, 2
%t3 = add i32 %t1, %t2
  ret i32 %t3
}

