; generated by weavec1

define i32 @main() {
entry:
%t0 = add i32 0, 40
%x.addr = alloca i32
  store i32 %t0, ptr %x.addr
%t1 = load i32, ptr %x.addr
%t2 = add i32 %t1, 2
  store i32 %t2, ptr %x.addr
%t3 = load i32, ptr %x.addr
  ret i32 %t3
}

