; generated by weavec1

define i32 @main() {
entry:
%x.addr = alloca i32
  store i32 40, ptr %x.addr
%t0 = load i32, ptr %x.addr
%t1 = add i32 %t0, 2
  store i32 %t1, ptr %x.addr
%t2 = load i32, ptr %x.addr
  ret i32 %t2
}

