; generated by weavec1
; source: tests/06_set_local.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let x
  %x.addr = alloca i32
  store i32 40, ptr %x.addr
  %t0 = load i32, ptr %x.addr
  %t1 = add i32 %t0, 2
  ; set x
  store i32 %t1, ptr %x.addr
  ; return
  %t2 = load i32, ptr %x.addr
  ret i32 %t2
}

