; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i32 0, 1
%t1 = add i32 0, 2
%t2 = icmp slt i32 %t0, %t1
  br i1 %t2, label %then0, label %else0
then0:
%t3 = add i32 0, 42
  ret i32 %t3
else0:
%t4 = add i32 0, 0
  ret i32 %t4
}

