; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i32 0, 0
%i.addr = alloca i32
  store i32 %t0, ptr %i.addr
%t1 = add i32 0, 0
%sum.addr = alloca i32
  store i32 %t1, ptr %sum.addr
  br label %while.cond0
while.cond0:
%t2 = load i32, ptr %i.addr
%t3 = add i32 0, 7
%t4 = icmp slt i32 %t2, %t3
  br i1 %t4, label %while.body0, label %while.end0
while.body0:
%t5 = load i32, ptr %sum.addr
%t6 = add i32 0, 6
%t7 = add i32 %t5, %t6
  store i32 %t7, ptr %sum.addr
%t8 = load i32, ptr %i.addr
%t9 = add i32 0, 1
%t10 = add i32 %t8, %t9
  store i32 %t10, ptr %i.addr
  br label %while.cond0
while.end0:
%t11 = load i32, ptr %sum.addr
  ret i32 %t11
}

