; generated by weavec1

define i32 @add(i32 %a, i32 %b) {
entry:
  ; return
  %t0 = add i32 %a, %b
  ret i32 %t0
}

define i32 @main() {
entry:
  ; return
  %t1 = call i32 @add(i32 20, i32 22)
  ret i32 %t1
}

