; generated by weavec1

declare i32 @puts(ptr)
@.str0 = private unnamed_addr constant [17 x i8] c"hello from weave\00"
define i32 @main() {
entry:
%t0 = getelementptr [17 x i8], ptr @.str0, i64 0, i64 0
  call i32 @puts(ptr %t0)
  ret i32 42
}

