; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

@.str0 = private unnamed_addr constant [17 x i8] c"hello from weave\00"

define i32 @main() {
entry:
%t0 = getelementptr [17 x i8], ptr @.str0, i64 0, i64 0
  call i32 @puts(ptr %t0)
%t1 = add i32 0, 42
  ret i32 %t1
}

