; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i64 0, 42
%x.addr = alloca i64
  store i64 %t0, ptr %x.addr
%t1 = load i64, ptr %x.addr
%t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

