; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i64 0, 20
%a.addr = alloca i64
  store i64 %t0, ptr %a.addr
%t1 = add i64 0, 2
%b.addr = alloca i64
  store i64 %t1, ptr %b.addr
%t2 = load i64, ptr %b.addr
%t3 = add i64 0, 11
%t4 = mul i64 %t2, %t3
%c.addr = alloca i64
  store i64 %t4, ptr %c.addr
%t5 = load i64, ptr %a.addr
%t6 = load i64, ptr %c.addr
%t7 = add i64 %t5, %t6
%d.addr = alloca i64
  store i64 %t7, ptr %d.addr
%t8 = load i64, ptr %d.addr
%t9 = trunc i64 %t8 to i32
  ret i32 %t9
}

