; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = or i1 false, true
%t1 = or i1 false, false
%t2 = or i1 false, true
%t3 = or i1 %t1, %t2
%t4 = and i1 %t0, %t3
  br i1 %t4, label %then0, label %else0
then0:
%t5 = add i32 0, 42
  ret i32 %t5
else0:
%t6 = add i32 0, 0
  ret i32 %t6
}

