; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t1 = add i64 0, 8
%t0 = call ptr @malloc(i64 %t1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t2 = load ptr, ptr %p.addr
%t3 = getelementptr i8, ptr null, i64 0
%t4 = icmp eq ptr %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
%t5 = add i32 0, 0
  ret i32 %t5
else0:
%t6 = load ptr, ptr %p.addr
  call void @free(ptr %t6)
%t7 = add i32 0, 42
  ret i32 %t7
}

