; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t1 = add i64 0, 16
%t0 = call ptr @malloc(i64 %t1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t2 = load ptr, ptr %p.addr
%t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t4 = load ptr, ptr %p.addr
%t5 = add i64 0, 20
  store i64 %t5, ptr %t4
%t6 = load ptr, ptr %p.addr
%t7 = getelementptr i8, ptr %t6, i64 8
%t8 = add i64 0, 22
  store i64 %t8, ptr %t7
%t9 = load ptr, ptr %p.addr
%t10 = load i64, ptr %t9
%a.addr = alloca i64
  store i64 %t10, ptr %a.addr
%t11 = load ptr, ptr %p.addr
%t12 = getelementptr i8, ptr %t11, i64 8
%t13 = load i64, ptr %t12
%b.addr = alloca i64
  store i64 %t13, ptr %b.addr
%t14 = load ptr, ptr %p.addr
  call void @free(ptr %t14)
%t15 = load i64, ptr %a.addr
%t16 = load i64, ptr %b.addr
%t17 = add i64 %t15, %t16
%t18 = trunc i64 %t17 to i32
  ret i32 %t18
}

