; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t1 = add i64 0, 1
%t0 = call ptr @malloc(i64 %t1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t2 = load ptr, ptr %p.addr
%t3 = getelementptr i8, ptr null, i64 0
%t4 = icmp eq ptr %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
%t5 = add i32 0, 0
  ret i32 %t5
else0:
  br label %done0
done0:
%t6 = load ptr, ptr %p.addr
%t7 = add i32 0, 42
%t8 = trunc i32 %t7 to i8
  store i8 %t8, ptr %t6
%t9 = load ptr, ptr %p.addr
%t10 = load i8, ptr %t9
%t11 = zext i8 %t10 to i32
%x.addr = alloca i32
  store i32 %t11, ptr %x.addr
%t12 = load ptr, ptr %p.addr
  call void @free(ptr %t12)
%t13 = load i32, ptr %x.addr
  ret i32 %t13
}

