; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t1 = add i64 0, 1
%t0 = call ptr @malloc(i64 %t1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t2 = load ptr, ptr %p.addr
%t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t4 = load ptr, ptr %p.addr
%t5 = add i32 0, 42
%t6 = trunc i32 %t5 to i8
  store i8 %t6, ptr %t4
%t7 = load ptr, ptr %p.addr
%t8 = load i8, ptr %t7
%t9 = zext i8 %t8 to i32
%x.addr = alloca i32
  store i32 %t9, ptr %x.addr
%t10 = load ptr, ptr %p.addr
  call void @free(ptr %t10)
%t11 = load i32, ptr %x.addr
  ret i32 %t11
}

