; generated by weavec1

; declarations

declare void @free(ptr)

define i32 @main() {
entry:
  ; call_void
  %t0 = getelementptr i8, ptr null, i64 0
  call void @free(ptr %t0)
  ; return
  ret i32 42
}

