; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i64 @answer64() {
entry:
%t0 = add i64 0, 42
  ret i64 %t0
}

define i32 @main() {
entry:
%t1 = call i64 @answer64()
%t2 = trunc i64 %t1 to i32
  ret i32 %t2
}

