; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define ptr @make_ptr() {
entry:
%t1 = add i64 0, 8
%t0 = call ptr @malloc(i64 %t1)
  ret ptr %t0
}

define i32 @main() {
entry:
%t2 = call ptr @make_ptr()
%p.addr = alloca ptr
  store ptr %t2, ptr %p.addr
%t3 = load ptr, ptr %p.addr
%t4 = getelementptr i8, ptr null, i64 0
%t5 = icmp eq ptr %t3, %t4
  br i1 %t5, label %then0, label %else0
then0:
%t6 = add i32 0, 0
  ret i32 %t6
else0:
%t7 = load ptr, ptr %p.addr
  call void @free(ptr %t7)
%t8 = add i32 0, 42
  ret i32 %t8
}

