; generated by weavec1
; source: tests/21_call_ptr.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: make_ptr
; params: none
; returns: ptr
define ptr @make_ptr() {
entry:
  ; return
  %t0 = call ptr @malloc(i64 8)
  ret ptr %t0
}

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t1 = call ptr @make_ptr()
  ; let p
  %p.addr = alloca ptr
  store ptr %t1, ptr %p.addr
  %t2 = load ptr, ptr %p.addr
  %t3 = icmp eq ptr %t2, null
  ; if condition
  br i1 %t3, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 0
else0:
  ; else
  ; call_void
  %t4 = load ptr, ptr %p.addr
  call void @free(ptr %t4)
  ; return
  ret i32 42
}

