; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define void @noop() {
entry:
  ret void
}

define i32 @main() {
entry:
  call void @noop()
%t0 = add i32 0, 42
  ret i32 %t0
}

