; generated by weavec1
; source: tests/24_buffer_like_smoke.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 24)
  ; let buffer
  %buffer.addr = alloca ptr
  store ptr %t0, ptr %buffer.addr
  %t1 = load ptr, ptr %buffer.addr
  %t2 = icmp eq ptr %t1, null
  ; if condition
  br i1 %t2, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 0
else0:
  ; else
  br label %done0
done0:
  %t3 = call ptr @malloc(i64 8)
  ; let data
  %data.addr = alloca ptr
  store ptr %t3, ptr %data.addr
  %t4 = load ptr, ptr %data.addr
  %t5 = icmp eq ptr %t4, null
  ; if condition
  br i1 %t5, label %then1, label %else1
then1:
  ; then
  ; call_void
  %t6 = load ptr, ptr %buffer.addr
  call void @free(ptr %t6)
  ; return
  ret i32 0
else1:
  ; else
  br label %done1
done1:
  ; store
  %t7 = load ptr, ptr %buffer.addr
  %t8 = load ptr, ptr %data.addr
  store ptr %t8, ptr %t7
  ; store
  %t9 = load ptr, ptr %buffer.addr
  %t10 = getelementptr i8, ptr %t9, i64 8
  %t11 = add i64 0, 1
  store i64 %t11, ptr %t10
  ; store
  %t12 = load ptr, ptr %buffer.addr
  %t13 = getelementptr i8, ptr %t12, i64 16
  %t14 = add i64 0, 8
  store i64 %t14, ptr %t13
  ; store
  %t15 = load ptr, ptr %data.addr
  %t16 = add i32 0, 42
  %t17 = trunc i32 %t16 to i8
  store i8 %t17, ptr %t15
  %t18 = load ptr, ptr %buffer.addr
  %t19 = load ptr, ptr %t18
  ; let data2
  %data2.addr = alloca ptr
  store ptr %t19, ptr %data2.addr
  %t20 = load ptr, ptr %data2.addr
  %t21 = load i8, ptr %t20
  %t22 = zext i8 %t21 to i32
  ; let x
  %x.addr = alloca i32
  store i32 %t22, ptr %x.addr
  ; call_void
  %t23 = load ptr, ptr %data.addr
  call void @free(ptr %t23)
  ; call_void
  %t24 = load ptr, ptr %buffer.addr
  call void @free(ptr %t24)
  ; return
  %t25 = load i32, ptr %x.addr
  ret i32 %t25
}

