; generated by weavec1

define i1 @same(i1 %x) {
entry:
  ret i1 %x
}

define i32 @main() {
entry:
%t0 = call i1 @same(i1 1)
  br i1 %t0, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

