; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i1 @same(i1 %x) {
entry:
%t0 = xor i1 false, %x
  ret i1 %t0
}

define i32 @main() {
entry:
%t2 = or i1 false, true
%t1 = call i1 @same(i1 %t2)
  br i1 %t1, label %then0, label %else0
then0:
%t3 = add i32 0, 42
  ret i32 %t3
else0:
%t4 = add i32 0, 0
  ret i32 %t4
}

