; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)

@.str1 = private unnamed_addr constant [28 x i8] c"hello from const_string_ptr\00"

define i32 @main() {
entry:
%t1 = getelementptr [28 x i8], ptr @.str1, i64 0, i64 0
%t0 = call i32 @puts(ptr %t1)
%t2 = add i32 0, 42
  ret i32 %t2
}

