; generated by weavec1

declare i32 @puts(ptr)
@.str1 = private unnamed_addr constant [28 x i8] c"hello from const_string_ptr\00"
define i32 @main() {
entry:
%t1 = getelementptr [28 x i8], ptr @.str1, i64 0, i64 0
%t0 = call i32 @puts(ptr %t1)
  ret i32 42
}

