; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i64 0, 50
%t1 = add i64 0, 8
%t2 = sub i64 %t0, %t1
%t3 = add i64 0, 42
%t4 = icmp eq i64 %t2, %t3
  br i1 %t4, label %then0, label %else0
then0:
%t5 = add i32 0, 42
  ret i32 %t5
else0:
%t6 = add i32 0, 0
  ret i32 %t6
}

