; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = or i1 false, false
%t1 = xor i1 %t0, true
  br i1 %t1, label %then0, label %else0
then0:
%t2 = add i32 0, 42
  ret i32 %t2
else0:
%t3 = add i32 0, 0
  ret i32 %t3
}

