; generated by weavec1
; source: tests/31_not_bool.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; if condition
  %t0 = or i1 false, false
  %t1 = xor i1 %t0, true
  br i1 %t1, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

