; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t1 = mul i64 2, 4
%t0 = call ptr @malloc(i64 %t1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t2 = load ptr, ptr %p.addr
%t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then0, label %else0
then0:
  ret i32 0
else0:
%t4 = load ptr, ptr %p.addr
  call void @free(ptr %t4)
  br label %done0
done0:
  ret i32 42
}

