; generated by weavec1
; source: tests/32_codegen_join_and_i64_arg.wir
; core-version: 1

; declarations

declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t1 = mul i64 2, 4
  %t0 = call ptr @malloc(i64 %t1)
  ; let p
  %p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
  ; if condition
  %t2 = load ptr, ptr %p.addr
  %t3 = icmp eq ptr %t2, null
  br i1 %t3, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 0
else0:
  ; else
  ; call_void
  %t4 = load ptr, ptr %p.addr
  call void @free(ptr %t4)
  br label %done0
done0:
  ; return
  ret i32 42
}

