; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t0 = call ptr @malloc(i64 1)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t1 = load ptr, ptr %p.addr
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%value.addr = alloca i32
  store i32 42, ptr %value.addr
%t3 = load ptr, ptr %p.addr
%t4 = load i32, ptr %value.addr
%t5 = trunc i32 %t4 to i8
  store i8 %t5, ptr %t3
%t6 = load ptr, ptr %p.addr
%t7 = load i8, ptr %t6
%t8 = zext i8 %t7 to i32
%loaded.addr = alloca i32
  store i32 %t8, ptr %loaded.addr
%t9 = load ptr, ptr %p.addr
  call void @free(ptr %t9)
%t10 = load i32, ptr %loaded.addr
  ret i32 %t10
}

