; generated by weavec1
; source: tests/34_ge_i32.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = icmp sge i32 42, 42
  ; if condition
  br i1 %t0, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 42
else0:
  ; else
  ; return
  ret i32 0
}

