; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i32 @main() {
entry:
%t0 = add i32 0, 50
%t1 = add i32 0, 8
%t2 = sub i32 %t0, %t1
  ret i32 %t2
}

