; generated by weavec1

define i32 @main() {
entry:
%t0 = icmp eq i32 42, 42
  br i1 %t0, label %then0, label %else0
then0:
  br label %done0
else0:
  ret i32 0
done0:
%t1 = icmp ne i32 42, 0
  br i1 %t1, label %then1, label %else1
then1:
  br label %done1
else1:
  ret i32 0
done1:
%t2 = icmp slt i32 1, 2
  br i1 %t2, label %then2, label %else2
then2:
  br label %done2
else2:
  ret i32 0
done2:
%t3 = icmp sle i32 2, 2
  br i1 %t3, label %then3, label %else3
then3:
  br label %done3
else3:
  ret i32 0
done3:
%t4 = icmp sgt i32 3, 2
  br i1 %t4, label %then4, label %else4
then4:
  br label %done4
else4:
  ret i32 0
done4:
%t5 = icmp sge i32 4, 4
  br i1 %t5, label %then5, label %else5
then5:
  ret i32 42
else5:
  ret i32 0
}

