; generated by weavec1

define i32 @main() {
entry:
%t0 = add i32 0, 42
%t1 = add i32 0, 42
%t2 = icmp eq i32 %t0, %t1
  br i1 %t2, label %then0, label %else0
then0:
  br label %done0
else0:
%t3 = add i32 0, 0
  ret i32 %t3
done0:
%t4 = add i32 0, 42
%t5 = add i32 0, 0
%t6 = icmp ne i32 %t4, %t5
  br i1 %t6, label %then1, label %else1
then1:
  br label %done1
else1:
%t7 = add i32 0, 0
  ret i32 %t7
done1:
%t8 = add i32 0, 1
%t9 = add i32 0, 2
%t10 = icmp slt i32 %t8, %t9
  br i1 %t10, label %then2, label %else2
then2:
  br label %done2
else2:
%t11 = add i32 0, 0
  ret i32 %t11
done2:
%t12 = add i32 0, 2
%t13 = add i32 0, 2
%t14 = icmp sle i32 %t12, %t13
  br i1 %t14, label %then3, label %else3
then3:
  br label %done3
else3:
%t15 = add i32 0, 0
  ret i32 %t15
done3:
%t16 = add i32 0, 3
%t17 = add i32 0, 2
%t18 = icmp sgt i32 %t16, %t17
  br i1 %t18, label %then4, label %else4
then4:
  br label %done4
else4:
%t19 = add i32 0, 0
  ret i32 %t19
done4:
%t20 = add i32 0, 4
%t21 = add i32 0, 4
%t22 = icmp sge i32 %t20, %t21
  br i1 %t22, label %then5, label %else5
then5:
%t23 = add i32 0, 42
  ret i32 %t23
else5:
%t24 = add i32 0, 0
  ret i32 %t24
}

