; generated by weavec0, the Weave Stage 0 compiler

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)
declare i32 @weave_compile_file(ptr, ptr)


define i1 @is_answer(i32 %x) {
entry:
%t0 = add i32 0, %x
%t1 = add i32 0, 42
%t2 = icmp eq i32 %t0, %t1
  ret i1 %t2
}

define i32 @main() {
entry:
%t4 = add i32 0, 42
%t3 = call i1 @is_answer(i32 %t4)
  br i1 %t3, label %then0, label %else0
then0:
%t5 = add i32 0, 42
  ret i32 %t5
else0:
%t6 = add i32 0, 0
  ret i32 %t6
}

