; generated by weavec1

define i1 @is_answer(i32 %x) {
entry:
%t0 = add i32 0, %x
%t1 = icmp eq i32 %t0, 42
  ret i1 %t1
}

define i32 @main() {
entry:
%t3 = add i32 0, 42
%t2 = call i1 @is_answer(i32 %t3)
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 42
else0:
  ret i32 0
}

