; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t0 = call ptr @malloc(i64 8)
%slot.addr = alloca ptr
  store ptr %t0, ptr %slot.addr
%t1 = load ptr, ptr %slot.addr
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t3 = call ptr @malloc(i64 8)
%data.addr = alloca ptr
  store ptr %t3, ptr %data.addr
%t4 = load ptr, ptr %data.addr
%t5 = icmp eq ptr %t4, null
  br i1 %t5, label %then1, label %else1
then1:
%t6 = load ptr, ptr %slot.addr
  call void @free(ptr %t6)
  ret i32 0
else1:
  br label %done1
done1:
%t7 = load ptr, ptr %slot.addr
%t8 = load ptr, ptr %data.addr
  store ptr %t8, ptr %t7
%t9 = load ptr, ptr %slot.addr
%t10 = load ptr, ptr %t9
%loaded.addr = alloca ptr
  store ptr %t10, ptr %loaded.addr
%t11 = load ptr, ptr %loaded.addr
%t12 = add i64 0, 42
  store i64 %t12, ptr %t11
%t13 = load ptr, ptr %data.addr
%t14 = load i64, ptr %t13
%value.addr = alloca i64
  store i64 %t14, ptr %value.addr
%t15 = load ptr, ptr %data.addr
  call void @free(ptr %t15)
%t16 = load ptr, ptr %slot.addr
  call void @free(ptr %t16)
%t17 = load i64, ptr %value.addr
%t18 = trunc i64 %t17 to i32
  ret i32 %t18
}

