; generated by weavec1
; source: tests/47_multiple_externs_used_subset.wir
; core-version: 1

; declarations

declare i32 @puts(ptr)
declare ptr @malloc(i64)
declare void @free(ptr)

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = call ptr @malloc(i64 8)
  ; let p
  %p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
  ; if condition
  %t1 = load ptr, ptr %p.addr
  %t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ; then
  ; return
  ret i32 0
else0:
  ; else
  br label %done0
done0:
  ; call_void
  %t3 = load ptr, ptr %p.addr
  call void @free(ptr %t3)
  ; return
  ret i32 42
}

