; generated by weavec1

declare ptr @malloc(i64)
declare void @free(ptr)
define i32 @main() {
entry:
%t0 = call ptr @malloc(i64 8)
%p.addr = alloca ptr
  store ptr %t0, ptr %p.addr
%t1 = load ptr, ptr %p.addr
%t2 = icmp eq ptr %t1, null
  br i1 %t2, label %then0, label %else0
then0:
  ret i32 0
else0:
  br label %done0
done0:
%t3 = load ptr, ptr %p.addr
  call void @free(ptr %t3)
  ret i32 42
}

