; generated by weavec1
; source: tests/48_string_escape.wir
; core-version: 1

; declarations

declare i32 @puts(ptr)

; string literals

@.str1 = private unnamed_addr constant [12 x i8] c"hello\0Aworld\00"
@.str3 = private unnamed_addr constant [15 x i8] c"quote: \22weave\22\00"
@.str5 = private unnamed_addr constant [13 x i8] c"backslash: \5C\00"

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  %t0 = getelementptr [12 x i8], ptr @.str1, i64 0, i64 0
  ; print
  call i32 @puts(ptr %t0)
  %t1 = getelementptr [15 x i8], ptr @.str3, i64 0, i64 0
  ; print
  call i32 @puts(ptr %t1)
  %t2 = getelementptr [13 x i8], ptr @.str5, i64 0, i64 0
  ; print
  call i32 @puts(ptr %t2)
  ; return
  ret i32 42
}

