; generated by weavec1
; source: tests/55_integration_nested_control_flow.wir
; core-version: 1

; function: main
; params: none
; returns: i32
define i32 @main() {
entry:
  ; let sum
  %sum.addr = alloca i64
  store i64 0, ptr %sum.addr
  ; let i
  %i.addr = alloca i64
  store i64 0, ptr %i.addr
  ; while condition
  br label %while.cond0
while.cond0:
  %t0 = load i64, ptr %i.addr
  %t1 = icmp slt i64 %t0, 10
  br i1 %t1, label %while.body0, label %while.end0
while.body0:
  ; while body
  ; if condition
  %t2 = load i64, ptr %i.addr
  %t3 = icmp sgt i64 %t2, 5
  br i1 %t3, label %then1, label %else1
then1:
  ; then
  ; set sum
  %t4 = load i64, ptr %sum.addr
  %t5 = load i64, ptr %i.addr
  %t6 = mul i64 %t5, 2
  %t7 = add i64 %t4, %t6
  store i64 %t7, ptr %sum.addr
  br label %done1
else1:
  ; else
  ; set sum
  %t8 = load i64, ptr %sum.addr
  %t9 = load i64, ptr %i.addr
  %t10 = add i64 %t8, %t9
  store i64 %t10, ptr %sum.addr
  br label %done1
done1:
  ; set i
  %t11 = load i64, ptr %i.addr
  %t12 = add i64 %t11, 1
  store i64 %t12, ptr %i.addr
  br label %while.cond0
while.end0:
  ; return
  %t13 = load i64, ptr %sum.addr
  %t14 = trunc i64 %t13 to i32
  ret i32 %t14
}

